# Homework: Create a madlib. Imagine a story where some of the words are 
# supplied by user input. Using python you will use input to collect 
# words for a story and then display the story. 

# Use input to collect each word to a variable
# Use an f string to display the story

# Your madlib must collect at least 6 words!

#FunctionsA
def display_design():
    print("/" *100)
    print("/" *100 + "\n")

import time

display_design()
print("Choose your own adventure Madlib!\n\nYou are a goblin in search of a cure for your ailing Aunt, Mabel.\nBefore you begin your quest, you stop to gather supplies.")
weapon = input("You take one item from the kitchen. What is it? ")
armour = input("You take one item from the bathroom. What is it? ")
display_design()
print("Your friend Snuffleblorg runs the local habberdashery. As fast as you can, you run to see them to see if there is anything they can give you to take on your adventure. ")
special_item = input("Snuffleblorg is generous! They give you a: ")
display_design()
print("As you make your way to the edge of your village, preparing to set off on your journey, an old crone who lives in a dilapidated shack at the edge of the Forbidden Forest suddenly stands in your path!\n")
time.sleep(5)
print("'Ho now, young Goblin!' the Crone screeches. 'You must not venture too far into the forest.'")
time.sleep(5)
print("Nervous, you explain your Aunt Mabel's condition is deteriorating and that you must find a cure for what plagues her.")
time.sleep(5)
print("The witch (because let's face it, she's a witch) pauses, staring at you with her one good eye.")
time.sleep(5)
print("'Oh, Mabel? Why didn't you say so?! Mabel and I go way back.'\n")
time.sleep(5)
print("'Still, the road ahead of you is treacherous. You must reach the centre of the forest and there you will find a well. At the bottom of the well is the cure you seek.'\n")
time.sleep(2)
print("The witch fumbles around under her cloak before presenting you a vial with a flourish.")
time.sleep(2)
print("'Here you go,' she tells you. 'In this vial is a potion for something or other. I forget what.'\n You gulp nervously. \n 'Drink it before you reach the centre of the forest and it will come to your aid when you need it most'.")
time.sleep(7)
print("Hastily, you hide the potion in your basket and carry on your way, all the time wondering what it might be - and hoping it is not poison.\n\n")
colour = input("What colour is the potion? :")
print("You enter the forest and are immediately faced with a fork in the path.\n")
route = input("Do you take the path to the left or the right? ")
display_design()
display_design()
print(f"Oh dear! Because you took the path on the {route} you immediately encounter the darkest, deadliest part of the forest. Before you know what is happening, a ghoul is blocking your way.")
time.sleep(2)
print("'Stop!' cries the ghoul. 'Who dares to break the shadows of the forest? Speak your name!\n")
name = input("Answer the nice ghoul: ")
print(f"'We have no need for goblins called {name} in the Forbidden Forest', the ghoul sneers, shimmering. 'If you're looking to exploit the Well of Wellness, I suggest you put your name on the list. But we're VERY exclusive. We don't have anything available until next January.")
time.sleep(2)
print(f"\nYou suddenly remember your {colour} vial from the witch. Quickly, you down the potion.\n")
print(f"Luckily, (ho!) the potion the witch provided is a LUCK potion. You should have paid more attention in Goblin school. Everyone knows Luck potions are a distinctive {colour}.")
time.sleep(10)
print("Tired of waiting, the ghoul suddenly rushes you, his face blurring into the mask of a demon!")
time.sleep(5)
print("You stagger back, but the luck potion is already doing its work. As you fall, your basket is upended.")
time.sleep(3)
print(f"In a MIRACULOUS turn of events your {weapon} bounces off a rock on the forest floor and flies directly into the ghoul's eyes.")
time.sleep(7)
print(f"Blinded, the ghoul tries to upend a dead tree, swinging it right for your head! With great fortune, the {armour} rolls under his trailing vapours and gets tangled in the trees roots. The upset in balance causes the tree to pass through the ghoul, dissipating his ghostly form.")
display_design()
display_design()
print(f"{name} is victorious! Now all that remains is for you to get the cure from the Well of Wellness.")
time.sleep(5)
print(f"You approach the Well of Wellness and read the sign next to the lever.")
display_design()
print(f"COST OF ADMISSION: ONE {special_item.upper()}")
display_design()
print(f"Thinking about how lucky that is, you settle down the {special_item} next to the Well and step back. It shimmers into gold. The payment is accepted.\n In the Well's bucket, there appears a magic poultice full of the herbs that will cure Aunt Mabel.")
time.sleep(10)
print("You return to the village and immediately give Aunt Mabel her medicine. She perks up instantly.\n")
time.sleep(2)
print(f"As word spreads of your derring do, all the villagers decide to henceforth call you {name} The Fortunate.")
display_design()
print("THE END")
display_design()
exit()